name: Build and Deploy Pages

on:
  push:
    branches: ["master"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.12
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v4

      - name: Get dependencies
        run: go get -v -t -d ./...

      - name: Build
        run: |
          cd web
          cp "$$(go env GOROOT)/misc/wasm/wasm_exec.js" .
          cp -r ../testdata .
          GOARCH=wasm GOOS=js go build -ldflags="-s -w" -o main.wasm main.go

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: "./web"

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
